### Creade Task
POST localhost:8080/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiUk9MRV9BRE1JTiIsInN1YiI6IjIyMjIyMjIiLCJpYXQiOjE3MzQxMTM0MjIsImV4cCI6MTczNjcwNTQyMn0.rGWMOCER6If6fB5e9EvSvXEsT_SwiAeFKWjrOzU7tmM

{
  "title": "Sartarosh",
  "content": "Soch oldirish kerak"
}


### Get All Task
GET localhost:8080/task


### Get All Task
GET localhost:8080/task/my
Authorization: Basic MTExMTExMToxMTEx


### Update Task
PUT localhost:8080/task/1286cdc1-1153-402e-85b3-89a0a5b1e2bc
Content-Type: application/json
Authorization: Basic MTExMTExMToxMTEx

{
  "title": "Sartarosh2",
  "content": "Soch oldirish kerak"
}


### Delete Task
DELETE localhost:8080/task/d2287779-1ceb-41f1-acb9-e47ab2dbdc35
Authorization: Basic dXNlcjoyNzkx


### Delete Task Admin
DELETE localhost:8080/task/1286cdc1-1153-402e-85b3-89a0a5b1e2bc/admin
Authorization: Basic MjIyMjIyMjoyMjIy