### Registration Profile
POST localhost:8080/user/registration
Content-Type: application/json

{
  "name": "G'ani",
  "surname": "G'aniyev",
  "phone": "2222222",
  "password": "2222",
  "role": "ROLE_ADMIN"
}


### Login
POST localhost:8080/user/authorization
Content-Type: application/json

{
  "phone": "2222222",
  "password": "2222"
}